### ISSUE TITLE
Will there be an alternative video plugin to use instead of Glide64?

### ISSUE THREAD

**Issue by DinoWattz** [Tarnadas/net64plus#119]

**Comment by themusicglitch** [comment]
lets hope they fix it for u lets hope they fix it for u and i wish they add youtube command

**Comment by twoBn** [comment]
![image](https://user-images.githubusercontent.com/60590727/87051896-2831d680-c1ce-11ea-9902-301d84f80f53.png)
and what do you mean by youtube command??
