### ISSUE TITLE
emulator scan problem

### ISSUE THREAD

**Issue by MailBoxSNES** [Tarnadas/net64plus#12]
I've  been stuck on change emulator, when ever i have Project 64 openNet64+ won't find the emulator that i opened can somebody help?

**Comment by Tarnadas** [comment]
Did you start PJ64 as default user oder admin?
Did you start Net64+ as default user or admin?

In task manager, please go to the details tab. Can you see there Project64.exe?

**Comment by Malcolm002** [comment]
I see it in the task manager and they are both ran as the same user.
And the emulator is in administrator mode but not net64+.

**Comment by Tarnadas** [comment]
That's why. Run Net64+ at least with the same privileges, so if you run PJ64 as admin, run Net64+ as admin as well

**Comment by Malcolm002** [comment]
I ran net64+ and project 64 1.6 both as administrator but it still doesn’t detect my emulator.

**Comment by Malcolm002** [comment]
Hello?

**Comment by Tarnadas** [comment]
Idk why it doesn't work.

You can try running both as default user or try PJ64 2.3

**Comment by Malcolm002** [comment]
I used project 64 2.3 and it still won’t find my emulator

**Comment by Malcolm002** [comment]
Btw I’m using Windows 8 64-bit for this

**Comment by Tarnadas** [comment]
Can you try starting your emulator and run the following command in a terminal:
```bash
tasklist
```

**Comment by Tarnadas** [comment]
Please try to use this version:

https://mega.nz/#!zMEh2DII!gyqL2lrNyStfMu0pzFRexLRj1-OSu_nWxFaW65xkkCE

I'll make a public release, if this works

**Comment by Malcolm002** [comment]
Still won't find my emulator, i used project 64 1.6 and 2.3 and nothing it's still on Scanning for emulators... thing.

**Comment by Tarnadas** [comment]
What about the tasklist command?

**Comment by Malcolm002** [comment]
Not yet still trying to figure out how to use it.

**Comment by Malcolm002** [comment]
I got a new computer and it works, turns out that Net64 or Net64+ doesn’t work right for Windows 8.1.

**Comment by Tarnadas** [comment]
Also the latest 1.1.2 release?

**Comment by Malcolm002** [comment]
Yes

**Comment by danitotop** [comment]
I HAVE EVERYTHING FINE AND DOESNT WORK
