### ISSUE TITLE
Net64 just sits at a yellow screen once launched

### ISSUE THREAD

**Issue by v0armd9** [Tarnadas/net64plus#123]
I'm not sure if this is something I am doing incorrectly, but I am only seeing a blank yellow screen when launching Net64. I have tried running as admin as well, but nothing changes. 
![Capture](https://user-images.githubusercontent.com/29674028/79058038-cb9e3a00-7c25-11ea-94af-448821592d10.PNG)

**Comment by twoBn** [comment]
this is a known issue and is being worked on

if you are in the net64 discord check #announcements

**Comment by v0armd9** [comment]
Is there a version that is working that I could use in the meantime?

**Comment by gaming32** [comment]
> Is there a version that is working that I could use in the meantime?

You can use version 2.4.
