### ISSUE TITLE
Suggestion: Better chat system (in-game chat) with "Advanced Text Engine"

### ISSUE THREAD

**Issue by GucciferSM64** [Tarnadas/net64plus#132]
I thought that for Net64+ 3.0 devs could make use of the "Advanced Text Engine" for SM64, created by jesusyoshi54. I could see it being useful for a more proper in-game chat rather than relying on colorful PrintXY function. 

Here is a video by jesusyoshi54, demonstrating the advanced text engine.
[![](http://img.youtube.com/vi/A-YfaQpm5-A/0.jpg)](http://www.youtube.com/watch?v=A-YfaQpm5-A "")

With the scrolling feature and a proper textbox background I could see this becoming a neat feature.

**Comment by GlowingUmbreon** [comment]
In 3.0 they are making the emulator and the client combined into one, it may be possible for the devs to overlay the chat over the emulator which would be much better than having mario 64 display the text.

**Comment by Tarnadas** [comment]
Please use the 3.0 for discussing 3.0 features:
https://github.com/net64-mod/net64-coop

Also as @GlowingUmbreon already said, it would be much better to integrate the chat with an overlay and let an actual UI handle the inputs rather than the game itself.
