### ISSUE TITLE
Net64 2.5.1 incompatibility with previous servers

### ISSUE THREAD

**Issue by DaffyDuck54** [Tarnadas/net64plus#134]
For some weird reason there is an incompatibility with some servers and this is version specific because when I use version 2.4 of net64 the server issue is gone

**Comment by Tarnadas** [comment]
What is the issue? What versions are affected?

**Comment by DaffyDuck54** [comment]
Version 2.5 and 2.5.1. Certain servers like Dizzy Abyess will say "Server Refused Connection. The server might not have set up the proper port forwarding or you insertedd a wrong port" This is definitely false because when i use 2.4 (or earlier versions) I connect to it fine. The reason why this is a problem is because 2.5 has features not present in 2.4.

**Comment by DaffyDuck54** [comment]
![Net64+ 2 5 1 4_21_2020 1_32_56 PM](https://user-images.githubusercontent.com/69287652/89558223-f2d6d380-d7e1-11ea-982e-0b66e0207b05.png)

**Comment by twoBn** [comment]
https://github.com/Tarnadas/net64plus-server/releases/tag/2.2.4

2.2.4 is from November 2019, I wouldn't be surprised if it broke on 2.5.x

**Comment by DaffyDuck54** [comment]
Yeah this is a problem since I had to download net64 2.4 just because of this.

**Comment by Tarnadas** [comment]
It's definitely not an incompatibility issue, since there was never a breaking change in the networking.
I have an idea why it broke, which is related to IP addresses not showing up since 2.5
