### ISSUE TITLE
Linux memory accessor lib

### ISSUE THREAD

**Issue by BPopcorn** [Tarnadas/net64plus#14]
I have a fully functional library for accessing sm64 on linux. Any way of implementing it?

**Comment by Tarnadas** [comment]
Can you link to it?
Linux support has rather low priority, but I might get back to it

**Comment by BPopcorn** [comment]
[https://gitlab.com/HenrikS/Net64plus-LinuxMemoryAccessor/tags](https://gitlab.com/HenrikS/Net64plus-LinuxMemoryAccessor/tags)

**Comment by BPopcorn** [comment]
if I recompile it it would work for mac, too
