### ISSUE TITLE
Net64+ not opening after computer crash

### ISSUE THREAD

**Issue by cratty79** [Tarnadas/net64plus#20]
My install of Net64+ won't open at all anymore. I can see there is a task through Task Manager, but no GUI opens. I've tried downloading it again, restarting my computer, and other things like that. Thanks!

**Comment by Tarnadas** [comment]
Please go to the folder %APPDATA%\net64plus and send me the file save.json

**DO NOT DELETE IT BEFORE SENDING ME THE FILE**

Delete it afterwards and you should be fine

**Comment by cratty79** [comment]
[save.json.txt](https://github.com/Tarnadas/net64plus/files/1689666/save.json.txt)
The renamed save.json, it's filled with null bytes. Which to me is weird.

**Comment by cratty79** [comment]
Apparently all I had to do was rename or delete the "net64plus" folder in %APPDATA% but thanks.

**Comment by Tarnadas** [comment]
Oh this looks weird. I'll make it more stable so it would just overwrite the save.json once it's corrupted

**Comment by cratty79** [comment]
Again, thanks for your help, I'll close the issue if it's OK.
