### ISSUE TITLE
Sync vs Async

### ISSUE THREAD

**Issue by UnseenFaith** [Tarnadas/net64plus#21]
There's a lot of places where you use sync versions, namely those from filesystem. Typically sync methods are discouraged due to the synchronous blocking nature of them. It would probably more beneficial from switching these sync methods back to their asynchronous version and not block the event loop, so that the process can continue working on other things. There's a few places where this wouldn't be possible, such as in class constructors, but for the most part it should be fine.

Is there any specific reason why sync versions are being used that I might be missing?

**Comment by Tarnadas** [comment]
It might just be because of laziness tbh. I'll go through all async calls and see if it should be changed

**Comment by UnseenFaith** [comment]
I'll be glad to help change them to the async versions if you'd like. You could also benefit from using the promisify function that was added in v8. Promisfied Functions  are much faster then just wrapping a function in a promise.

**Comment by Tarnadas** [comment]
How can the Node promisify wrapper be faster than doing it the regular Promise-like way?

I just pushed a few changes, that I've seen as critical. Would you say this resolves the issue?

**Comment by Tarnadas** [comment]
I would say this is resolved, because the rest of the sync functions in inside the build script
