### ISSUE TITLE
This App can't run on your PC - Windows 10 32 Bits

### ISSUE THREAD

**Issue by zfeikg** [Tarnadas/net64plus#27]
So, I downloaded Net64 some hours ago and this happens, when I try to open it it says that My PC can't run it, that windows pop-up when your device is not compatible, for me this pop-up only appears when I try to open a 64 bit .exe file.

**Comment by Thomakaze** [comment]
That would be because it's a 64 bit application...

**Comment by Thomakaze** [comment]
That would be because it's a 64 bit application...

**Comment by FateForWindows** [comment]
That's normal, since Net64 is 64 bit.
