### ISSUE TITLE
Gamemode votes not working 

### ISSUE THREAD

**Issue by Damongirl** [Tarnadas/net64plus#28]
I was trying to change game modes with a couple of friends today, and no matter what we did we couldn't vote on any of them. We tried typing in /gamemode 6 and it just wouldn't vote. I hope a fix for that releases soon.

**Comment by Tarnadas** [comment]
Did you not get any message at all after sending the command? Was it a server hosted with Node or a server hosted with the exe?

**Comment by Jean20B** [comment]
`[SERVER]: Gamemode vote passed with too few votes.` = RIP Gamemode

**Comment by Tarnadas** [comment]
Alright, I'll see if I did something wrong

**Comment by Tarnadas** [comment]
Fixed.

See: https://github.com/Tarnadas/net64plus-server/commit/27fbed1d87e8468d491bc81e2bc22a374d2b09ee

**Comment by Damongirl** [comment]
It was a server hosted with the exe file in the 2.0 release. And there wasn't a message after sending the command either.

**Comment by Damongirl** [comment]
Nice to see that this got fixed so quickly! Thanks a lot.
