### ISSUE TITLE
Minor Issue: New update glitch with Net64+ 2.0.1 - Says to update when I already have 2.0.1

### ISSUE THREAD

**Issue by SuperToad64** [Tarnadas/net64plus#35]
Nothing major but it is really annoying. When I downloaded Net64+ 2.0.1 it tells me to update to 2.0.1 when I already am using Net64+ 2.0.1. This has never happened before in any client. I was wondering if there was any way to turn off update notifications in Net64+. I don't want to press Ignore every time I have to set up Net64+. Since I set up a LAN server at my house it is annoying to keep pressing Ignore every time. Any help would be greatly appreciated, thanks! :)

**Comment by Tarnadas** [comment]
Yeah sorry, it was because of the tag on GitHub, which was v2.0.1 instead of 2.0.1

It should be working now.

**Comment by SuperToad64** [comment]
Thanks! It works now. :)
