### ISSUE TITLE
Net64+ wont open.

### ISSUE THREAD

**Issue by Unpainfulflork** [Tarnadas/net64plus#38]
I have installed Super Mario 64 online successfully on other computers, but here it seems that Net64 wont open. I have tried going into appdata and deleting the save.json file, but the only thing in that folder is another folder named logs which is empty. I have tried reinstalling twice and resetting this computer but each time im unsuccessful. Any ideas on how i could fix this??

**Comment by Tarnadas** [comment]
Have you check Windows Defender and your Antivirus software? Net64+ could be treated as a false positive

**Comment by unenergizer** [comment]
I have BitDefender antivirus. While it would allow the program to run, it would effect it and prevent me from running the roms. Adding the emulator and client as an exception fixed these issues for me. As Tarnadas said, give it a shot and see how it goes! Good luck!
