### ISSUE TITLE
Opening the file

### ISSUE THREAD

**Issue by Dastebil** [Tarnadas/net64plus#40]
I have problems with opening the file and I have tried all the 3 downloads.

**Comment by Dastebil** [comment]
What is 7zip and how can I get it?

**Comment by Dastebil** [comment]
Thanks and do you now how to use labels?

**Comment by BPopcorn** [comment]
On github?

**Comment by Dastebil** [comment]
Yes.

**Comment by Dastebil** [comment]
Ok. Thanks for the help :)

**Comment by Dastebil** [comment]
I still can't open the file

**Comment by weshuiz** [comment]
getting this error when i loading a rom into the emulator
CN64Systeem::EmulationStarting Exeption caught File: N64 System\N4 Class.cpp Line: 259
