### ISSUE TITLE
erm. nice textures

### ISSUE THREAD

**Issue by Bigpro19000** [Tarnadas/net64plus#41]
https://youtu.be/zv68v450fCo

**Comment by Xhizors24** [comment]
More info please. Did you use the emulator bundled with the client, and set memory to 16MB etc? Windows version?

**Comment by Bigpro19000** [comment]
yes. I know how this works and normally everything is good. 

Win 10
GTX 1060 TI
Some I7 processor
16GB DDR4

**Comment by Dastebil** [comment]
Mabye the server glitcedout? (Note: I am a Swedish person so my writing might be bad)

**Comment by sbmn** [comment]
I have a theory for this. This has to do with the injection being interrupted. The reason is because in the older versions if it broke half way through it generally made the strange tilting effect on all the characters.

**Comment by Bigpro19000** [comment]
hmm I guess this is weird ;p

**Comment by SuperToad64** [comment]
I know what the problem is. You probably changed the graphics plugin. You CANNOT do this, or it will screw up the textures like that. I know for a fact this is what happened because it happened to me when I tried. You have to be using the Glide64 Napalm Release 1 plugin that is included with Project64 2.2 MM. If you don't things like that will happen. So make sure you are running the right graphics plugin.

**Comment by Tarnadas** [comment]
@Bigpro19000 can you verify, that this resolves your issue?

**Comment by Bigpro19000** [comment]
I am defiantly using Glide64 Napalm Release 1.0 as I just checked

**Comment by Tarnadas** [comment]
There's a section in the FAQ:

"The graphics look pixelated?

This happens when you press backspace on your keyboard. It's a feature that changes the filtering mode between Bilinear, Point-Sampled, and Automatic. Just press backspace again to set it back to normal."

Does this work?

**Comment by Bigpro19000** [comment]
I know about that and it does nothing ;p also it only occurs when I'm in a big lobby

**Comment by Bigpro19000** [comment]
nope ;p

**Comment by Tarnadas** [comment]
Any update on this issue? Do you still have this problem?
