### ISSUE TITLE
I have a suggestion.

### ISSUE THREAD

**Issue by FireSonicGH** [Tarnadas/net64plus#45]
You should really buff Kirby; his downsides are even worse than the Goomba's.

**Comment by SuperToad64** [comment]
Are you serious? Kirby is like the most OP character in Net64+. He can jump five times in mid-air and he doesn't have any fall damage. He also doesn't have less health like knuckles. He is a bit slow, but that is done to balance out the character. I think Kirby is fine just the way he is.

**Comment by DizzyThermal** [comment]
Kirby is a handicap character. From my understanding, Kirby is for players unfamiliar with SM64 and would like/need a more "forgiving" character.

**Comment by Tarnadas** [comment]
Please keep character discussions on the Discord server or [Reddit](https://reddit.com/r/Net64).

Closing because of this
