### ISSUE TITLE
servers down?

### ISSUE THREAD

**Issue by Bigpro19000** [Tarnadas/net64plus#48]
so all today I have been trying to play. It just says fetching server list then not able to. So I went on the internet searched it up went onto the official website and my PC wouldn't connect to that. :( luckily direct connect still works. So does anyone know what happend? or if anyone else has this same problem?

**Comment by SuperToad64** [comment]
Yeah it happens to me as well. But I don't play on public servers so it doesn't effect me. Maybe SM64O got a DMCA claim and the servers are down because of that.

**Comment by Tarnadas** [comment]
Server will be back online soon
