### ISSUE TITLE
Opening the file

### ISSUE THREAD

**Issue by Dastebil** [Tarnadas/net64plus#51]
The file can´t open even with 7-zip

**Comment by fancymelonub** [comment]
You don't open the EXE with 7zip, idiot.

**Comment by Dastebil** [comment]
I don't even have an EXE file in the folder!

**Comment by Essasetic** [comment]
Did you extract the zip?

**Comment by Essasetic** [comment]
Have you tried going inside the 2 folders when you have extracted the zip?

**Comment by Dastebil** [comment]
2? I have 4 folders.

**Comment by Essasetic** [comment]
Inside the Net64+ folder?

**Comment by Dastebil** [comment]
yes

**Comment by Essasetic** [comment]
Please share a screenshot of the folders.

**Comment by Dastebil** [comment]
how do I screenshot?

**Comment by Essasetic** [comment]
*sigh* there's a print screen key on your keyboard.

**Comment by Dastebil** [comment]
yes and I pressed it but I got no screenshot

**Comment by Essasetic** [comment]
You are meant to paste it in.

**Comment by Dastebil** [comment]
Paste it in?

**Comment by Essasetic** [comment]
Just press ctrl key then the v key.

**Comment by Dastebil** [comment]
![image](https://user-images.githubusercontent.com/39271964/40586804-6b8789ba-61dc-11e8-8109-9b0384260f62.png)

**Comment by Dastebil** [comment]
![image](https://user-images.githubusercontent.com/39271964/40586809-89977582-61dc-11e8-9188-9364225801d4.png)

**Comment by Essasetic** [comment]
Do you want to HOST a server?

**Comment by Essasetic** [comment]
*faceplam* you downloaded the source code

**Comment by Dastebil** [comment]
no but to join (and open the file)

**Comment by Essasetic** [comment]
https://github.com/Tarnadas/net64plus/releases/download/2.0.1/Net64plus_2.0.1-win32-x64.7z download this.

**Comment by Dastebil** [comment]
![image](https://user-images.githubusercontent.com/39271964/40586869-2c76f502-61dd-11e8-935b-acb81b97927b.png)

**Comment by Benedani** [comment]
This discussion is making me facepalm so hard

**Comment by Essasetic** [comment]
Do you even have 7zip?

**Comment by Dastebil** [comment]
yes

**Comment by Dastebil** [comment]
![image](https://user-images.githubusercontent.com/39271964/40586896-7fd6207e-61dd-11e8-8888-eefb82d0dfea.png)

**Comment by Essasetic** [comment]
Did you install it? If you do have it installed the .7z would have a 7zip icon on it.

**Comment by Dastebil** [comment]
yes and no

**Comment by Essasetic** [comment]
*sigh* did you install it with a .exe?

**Comment by Dastebil** [comment]
there was no exe option

**Comment by Essasetic** [comment]
7zip: https://www.7-zip.org/a/7z1805-x64.exe

**Comment by Dastebil** [comment]
Ohhhhhhhhhh. yes I downloaded it with exe

**Comment by Essasetic** [comment]
Ok now right click on the 7z file, hover over the option that says 7zip, then press on extract to *folder name*

**Comment by Dastebil** [comment]
Like this 
![image](https://user-images.githubusercontent.com/39271964/40587095-144d7fde-61e0-11e8-8608-cfabbe7df493.png)

**Comment by Bigpro19000** [comment]
no right click on net64 xd

**Comment by Dastebil** [comment]
IT DOES NOT WORK!

**Comment by Essasetic** [comment]
What doesn't work?

**Comment by BPopcorn** [comment]
Issues are for technical questions & bug reports. If you need help on how to use a computer please ask on our discord server: 
[![Discord](https://discordapp.com/api/guilds/354358899328942081/widget.png)](https://discord.gg/net64)

**Comment by Dastebil** [comment]
The 7 zip thing
