### ISSUE TITLE
net64 2.1 cant detect the built in emulator windows 7

### ISSUE THREAD

**Issue by natedogbake** [Tarnadas/net64plus#61]
i have made exceptions in my firewall i have them both running in admin and windows compatibility for windows 7 i have asked people on the net64 discord and nobody can help me the emulator has 16mb set and counter rate set to 1 i tried redownloading and doing it all over that didnt work and i even tried doing it on a earlier version and it still didnt work

**Comment by natedogbake** [comment]
https://cdn.discordapp.com/attachments/442725107501236234/488148854533783554/unknown.png
pic of the net64

**Comment by natedogbake** [comment]
if instead of the net64 automatically scanning we could choose from like a task manager list of open programs to attach to that would probably work

**Comment by Tarnadas** [comment]
Could you try running tasklist as a command inside a terminal? This is what's internally used by Net64+ to detect the emulator

**Comment by natedogbake** [comment]
this problem was actually for my sister and i have been trying to solve it and opened it up in her stead 
after you told me to try using tasklist it didnt recognize the command so i dug around and found that you need your enviroment variables system PATH set to system 32 for it to be recognized hers instead was C:\Program Files\Java\jdk1.8.0_171\bin;C:\ProgramFiles\Java\jre1.8.0_171\bin;%GRADLE_HOME%\bin
now that i changed it to C:\Windows\System32; it was fixed and her net64 can now detect the emulator
thank you for your help if you hadnt let me know that tasklist was the problem i couldnt of figured it out
