### ISSUE TITLE
One-click server hosting

### ISSUE THREAD

**Issue by Tarnadas** [Tarnadas/net64plus#64]
To facilitate server hosting for user servers, a one-click start and join solution will be implemented.

For checking whether a port is forwarded correctly, smmdb should have an API endpoint, which tries to connect to the WebSocket Port.
It should therefore show:
- whether Port has been forwarded correctly
- the users WAN IP address

**Comment by fancymelonub** [comment]
Oooo, can servers opened by this one-click button can be public? It would be cool, or at least have a different server list for servers ran by the already-compiled (release tab binaries) server versions or the one-click server thing.

**Comment by Tarnadas** [comment]
Yes they can be public. I added another icon into the server list to indicate whether it is a dedicated server or a user server and you will be able to filter for that.
It internally uses the precompiled binary which can now accept arguments for settings.
