### ISSUE TITLE
Split-screen multiplayer

### ISSUE THREAD

**Issue by zrksyd** [Tarnadas/net64plus#65]
Is it possible to implement split-screen multiplayer using most of what is already done by Net64? Perhaps it could communicate through multiple instances of Project64 if the limit of having one instance of Project64 run is removed?

**Comment by halloweeniez** [comment]
It's possible to do this by having two instances of both net64 and pj64 open. As you can inject one to each Net64 open.

**Comment by zrksyd** [comment]
Fair enough, but can we have a built-in easier way of going about it? Not to mention, it would unnecessarily being communicating through the server.
