### ISSUE TITLE
Low-Latency Mode?

### ISSUE THREAD

**Issue by adamthecoolest** [Tarnadas/net64plus#67]
Please forgive me if I'm wrong, but as far as I know, net64plus does not have this. I feel like if there was a low-latency mode, it could really help out some users who don't have great internet.

**Comment by BPopcorn** [comment]
What exactly would a low-latency mode do? What if net64 was already doing it by default?

**Comment by adamthecoolest** [comment]
> What exactly would a low-latency mode do? What if net64 was already doing it by default?

Well, I was thinking it could possibly somehow lower the amount of things going on. Here is an example: Say there is a lot of players in one server, in this case, I think a good way to utilize low-latency would be to unload all of the players until they are in the same area as you, in which then they would be re-loaded into the game.

**Comment by Henrik2000** [comment]
Theoretically this would be possible but would increase the bandwidth requirements for the host. It might also break some minigames.

**Comment by adamthecoolest** [comment]
> Theoretically this would be possible but would increase the bandwidth requirements for the host. It might also break some minigames.

Well, if it does indeed break minigames, then there could be a warning before enabling the feature to address the problem.

**Comment by adamthecoolest** [comment]
> How exactly does poor internet affect online play for you?
> 
> Also low latency makes no sense, because that would be good. You either mean high latency (time for a message to travel from client to server) or low bandwidth. Net64 already has low bandwidth, but there would theoretically be another compression optimization that I would want to do. What Henrik said was already planned some day, but with the release of Minigames would be impossible.
> 
> If you need a better latency, you would have to join servers that are geographically nearer to your location

Hmm... I see. Well, if that's the case, do you want me to close this issue?

**Comment by Tarnadas** [comment]
Yeah I think we can do that, if there's nothing else I can help you with

**Comment by adamthecoolest** [comment]
Alright, thank you @Tarnadas and @Henrik2000 for giving me your input on my idea. This issue is now closed.
