### ISSUE TITLE
Players without password receiving IDs and spamming the console.

### ISSUE THREAD

**Issue by EnchantedTorch** [Tarnadas/net64plus#75]
It seems like whenever anyone attempts to join a server, with or without the password needed to connect, they're given a player ID. When this occurs on a password protected server, it results in constant console updates whenever someone attempts to join and then quits out after realizing they can't connect.

**Comment by Tarnadas** [comment]
Hey,
Thanks for the request.
This bug is already fixed on the dev branch and will soon be publiahed

**Comment by Tarnadas** [comment]
Fixed in 2.2
