### ISSUE TITLE
Game Crashing, Memory Error? 

### ISSUE THREAD

**Issue by Aurora5992** [Tarnadas/net64plus#77]
After playing around in a server for a mere few seconds, all I get is this. 
https://photos.app.goo.gl/ddXyEXXtZs1aJqN68

**Comment by fancymelonub** [comment]
1. Did you use the emulator that came in the zip file?
2. Did you set SM64 to 16MB RAM and Counter Factor to 1?

**Comment by Aurora5992** [comment]
> 
> 
>     1. Did you use the emulator that came in the zip file?
> 
>     2. Did you set SM64 to 16MB RAM and Counter Factor to 1?

Yes and yes. No idea what's going wrong here.
