### ISSUE TITLE
No 32-bit support

### ISSUE THREAD

**Issue by GamingGage** [Tarnadas/net64plus#81]
I have a 32-bit OS installed on my laptop, so I can't use net64.

**Comment by Jean20B** [comment]
#27

**Comment by GamingGage** [comment]
Does that mean it will be fixed next version?

**Comment by Jean20B** [comment]
No

https://github.com/Tarnadas/net64plus/issues/27#issuecomment-387035220
> 32bit support won't be implemented, sorry.
> There are dependencies which rely on 64bit and I cannot compile them to 32bit
