### ISSUE TITLE
It Freezes when the character is going to jump

### ISSUE THREAD

**Issue by TheNemix** [Tarnadas/net64plus#82]
When the character is going to jump out of the pipe it freezes , but u can still hearing the birds and that , also the lives icon is with a weird texture.

**Comment by fancymelonub** [comment]
Is the game set to use 16MB RAM and has Counter Factor set to 1?
![image](https://user-images.githubusercontent.com/30706150/51951385-6c7a4e00-2402-11e9-8d35-1b2e32c575b8.png)

**Comment by TheNemix** [comment]
yep
