### ISSUE TITLE
Add Course Name Indicator

### ISSUE THREAD

**Issue by DizzyThermal** [Tarnadas/net64plus#9]
Hello, I wasn't sure if this would be an interesting feature/enhancement to net64plus, but I think it would be useful. I used Cheat Engine to find what I believe to be the memory location for where a player is in in-game.

Memory Address (from Cheat Engine):
`0x50B2BAC4`

This appears to hold the Course # of the player.

I went through the levels and collected their numbers:
```
  00 - MAIN (Castle/Courtyard/Outside)
  01 - BOB (Bob-omb Battlefield)
  02 - WF (Whomp's Fortress)
  03 - JRB (Jolly Roger Bay)
  04 - CCM (Cool, Cool Mountain)
  05 - BBH (Boo's Big Haunt)
  06 - HMC (Hazy Maze Cave)
  07 - LLL (Lethal Lava Land)
  08 - SSL (Shifting Sand Lang)
  09 - DDD (Dire, Dire Docks)
  10 - SL (Snowman's Land)
  11 - WDW (Wet-Dry World)
  12 - TTM (Tall, Tall Mountain)
  13 - THI (Tiny Huge Island)
  14 - TTC (Tick-Tock Clock)
  15 - RR (Rainbow Ride)
  16 - BitDW (Bowser in the Dark World)
  17 - BitFS (Bowser in the Fire Sea)
  18 - BitS (Bowser in the Sky)
  19 - PSS (Peach's Secret Slide)
  20 - MC (Metal Cap)
  21 - WC (Wing Cap)
  22 - VC (Vanish Cap)
  23 - OTR (Wing Mario Over The Rainbow)
  24 - SA (Secret Aquarium)
```

What would be cool is to put the acronyms for the courses to the left of the player character in the player list:

`[Course Acronym] [Player Character Icon] [Player Name]`

Have any thoughts? Thanks!

**Comment by Tarnadas** [comment]
The player data array also holds this data in an easier accessible way, but I like the idea.
I might add this for the next version

**Comment by DizzyThermal** [comment]
@Tarnadas a related idea would be a star count indicator.

New players entering in could see where all the players are - star wise. Not as useful as a course indicator, but informative.

Thanks!

**Comment by frozenLake** [comment]
Note this should probably only be used if the Rom is Vanilla, since romhacks are bound to screw with this system.

**Comment by DizzyThermal** [comment]
I did a bit more digging on this.

Starting with the address: `0x367700` (Player Data) and reading `0x18` (24 bytes), if we look at:

`player_data[0xF] = Course`

I went into every level / room to record these values (30 values total):

```
  4 = Boo's Big Haunt
  5 = Cool, Cool Mountain
  6 = Castle Lobby
  7 = Hazy Maze Cave
  8 = Shifting Sand Land
  9 = Bob-omb's Battlefield
  10 = Snowman's Land
  11 = Wet-Dry World
  12 = Jolly Roger Bay
  13 = Tiny-Huge Island
  14 = Tick Tock Clock
  15 = Rainbow Ride
  16 = Outside of Castle
  17 = Bowser in the Dark World - MAIN
  18 = Vanish Cap Under the Moat
  19 = Bowser in the Fire Sea - MAIN
  20 = Secret Aquarium
  21 = Bowser in the Sky - MAIN
  22 = Lethal Lava Land
  23 = Dire, Dire Docks
  24 = Whomp's Fortress
  26 = Castle Courtyard
  27 = Peach's Secret Slide
  28 = Cavern of the Metal Cap
  29 = Tower of the Wing Cap
  30 = Bowser in the Dark World - BOSS
  31 = Wing Mario Over the Rainbow
  33 = Bowser in the Fire Sea - BOSS
  34 = Bowser in the Sky - BOSS
  36 = Tall, Tall Mountain
```

_Note: Bowser stages are broken up into MAIN/BOSS and Outside/Castle Lobby/Castle Courtyard are different value - which is why there are 30 entries above and only 25 icons below._

SM64 icons: [courses.zip](https://github.com/Tarnadas/net64plus/files/1624982/courses.zip)
[Source](https://www.reddit.com/r/speedrun/comments/27fvua/for_sm64_runners_in_search_of_split_icons/)

Then we can make a dictionary of the course number-to-image mappings from the list above:

```
courses = {
  4: "05-bbh.png",
  5: "04-ccm.png",
  6: "00-castle.png",
  7: "06-hmc.png",
  8: "08-ssl.png",
  9: "01-bob.png",
  10: "10-sl.png",
  11: "11-wdw.png",
  12: "03-jrb.png",
  13: "13-thi.png",
  14: "14-ttc.png",
  15: "15-rr.png",
  16: "00-castle.png",
  17: "16-bitdw.png",
  18: "22-vanish.png",
  19: "17-bitfs.png",
  20: "24-aqua.png",
  21: "18-bits.png",
  22: "07-lll.png",
  23: "09-ddd.png",
  24: "02-wf.png",
  26: "00-castle.png",
  27: "19-pss.png",
  28: "20-metal.png",
  29: "21-wing.png",
  30: "16-bitdw.png",
  31: "23-sky.png",
  33: "17-bitfs.png",
  34: "18-bits.png",
  36: "12-ttm.png"
}
```

The only thing that I am unsure of is how player data can identify _who_ sent the data being received. I'm not sure if ID is somewhere in the player_data, or not?

Once I can figure that out I could then save the locations for each user as onMessage(data) is received to render the icon next to their character icon.

**Comment by Tarnadas** [comment]
It's the 3rd byte that holds player ID. Thx for your research btw. I will definitely implement this for 2.0

**Comment by DizzyThermal** [comment]
Thanks for that info, I slapped together a working prototype [in my fork](https://github.com/DizzyThermal/net64plus)

I think the only aspect that doesn't work is your _own_ location (since the way I have it, it only updates the playerCourseId when a message is received [you don't send your own player_data to yourself])
